"""Drive opencode headless to power the Slow Track.

The Fast Track has already actuated the device. For the *reflection* (in-character
chatter), we ask the real opencode engine to run the relevant subagent::

    opencode run --agent <id> --model <provider/model> "<event context>"

If the ``opencode`` binary is not installed, the runner falls back to a clearly
labelled dry-run so the rest of the OS keeps working (and tests stay hermetic).
"""

from __future__ import annotations

import json
import shutil
import subprocess
from dataclasses import dataclass

from ...bridge.event_bus import EventBus
from ...bridge.events import SystemEvent
from ...routing.slow_track import SlowTrackSpawner


@dataclass
class RunResult:
    ok: bool
    text: str
    agent: str
    dry_run: bool = False
    returncode: int | None = None
    raw: str = ""


class OpencodeRunner:
    def __init__(
        self,
        binary: str = "opencode",
        cwd: str | None = None,
        model: str | None = None,
        timeout: float = 120.0,
        dry_run: bool | None = None,
    ) -> None:
        self.binary = binary
        self.cwd = cwd
        self.model = model
        self.timeout = timeout
        self.available = shutil.which(binary) is not None
        # Auto dry-run when the binary is missing, unless explicitly overridden.
        self.dry_run = (not self.available) if dry_run is None else dry_run

    def run(self, agent_id: str, message: str, model: str | None = None) -> RunResult:
        if self.dry_run:
            return RunResult(
                ok=True, agent=agent_id, dry_run=True,
                text=f"[opencode dry-run] {agent_id} would reflect on: {message}",
            )
        cmd = [self.binary, "run", "--agent", agent_id]
        mdl = model or self.model
        if mdl:
            cmd += ["--model", mdl]
        cmd.append(message)
        try:
            proc = subprocess.run(
                cmd, cwd=self.cwd, capture_output=True, text=True, timeout=self.timeout,
            )
        except (subprocess.TimeoutExpired, FileNotFoundError) as exc:  # pragma: no cover - env dependent
            return RunResult(ok=False, agent=agent_id, text=f"opencode run failed: {exc}", returncode=None)
        return RunResult(
            ok=proc.returncode == 0,
            agent=agent_id,
            text=(proc.stdout or proc.stderr).strip(),
            returncode=proc.returncode,
            raw=proc.stdout,
        )


class OpencodeSlowTrack(SlowTrackSpawner):
    """A Slow Track whose in-character reflections are generated by opencode."""

    def __init__(
        self,
        bus: EventBus,
        runner: OpencodeRunner | None = None,
        reflection_delay: float = 0.0,
    ) -> None:
        self.runner = runner or OpencodeRunner()
        super().__init__(bus, reaction_fn=self._reflect, reflection_delay=reflection_delay)

    def _reflect(self, agent_id: str, event: SystemEvent) -> str:
        context = (
            f"A change just happened in your space. Event: {event.to_context_text()}. "
            f"React in character (1-2 sentences)."
        )
        result = self.runner.run(agent_id, context)
        return result.text
