"""Configuration schema produced by the Meta-Agent (Stage 4) and consumed by
the orchestrator / hot-reloader.

The *external* schema (what the Meta-Agent LLM returns and what we
``json.loads`` directly) is intentionally exactly the contract the user
specified:

    {
      "system_domain": {"name": ..., "background_lore": ...},
      "agents": [
        {
          "id", "name", "role", "tone_of_voice",
          "permissions": {"read_only_entities": [...], "execute_entities": [...]},
          "proactive_triggers": ["natural language condition", ...]
        }
      ]
    }

``proactive_triggers`` are free-text on purpose -- the backend
(:class:`~agile_agentic_os.orchestration.triggers.TriggerParser`) compiles them
into structured :class:`CompiledTrigger` objects bound to State-Changed events.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from ..guardrails.models import LimitRule, Permission


class SystemDomain(BaseModel):
    name: str
    background_lore: str = ""


class AgentPermissions(BaseModel):
    """RBAC split: what an agent may *see* vs. what it may *actuate*."""

    read_only_entities: list[str] = Field(default_factory=list)
    execute_entities: list[str] = Field(default_factory=list)

    def all_entities(self) -> list[str]:
        seen: list[str] = []
        for e in [*self.read_only_entities, *self.execute_entities]:
            if e not in seen:
                seen.append(e)
        return seen


class AgentSpec(BaseModel):
    # Tolerate (and ignore) any extra keys an LLM might add.
    model_config = ConfigDict(extra="ignore")

    id: str
    name: str = ""
    role: str = ""
    tone_of_voice: str = "neutral, concise"
    permissions: AgentPermissions = Field(default_factory=AgentPermissions)
    proactive_triggers: list[str] = Field(default_factory=list)
    # Optional runtime-only field (not part of the LLM contract).
    system_prompt: str = ""

    def model_post_init(self, __context) -> None:
        if not self.name:
            self.name = self.id


class OSConfig(BaseModel):
    model_config = ConfigDict(extra="ignore")

    system_domain: SystemDomain
    agents: list[AgentSpec] = Field(default_factory=list)
    # Backend-side safety limits (generated by the planner, not by the LLM).
    limits: list[LimitRule] = Field(default_factory=list)

    @property
    def domain(self) -> str:
        return self.system_domain.name

    def entity_ids(self) -> set[str]:
        out: set[str] = set()
        for a in self.agents:
            out.update(a.permissions.all_entities())
        return out


class CompiledTrigger(BaseModel):
    """A structured trigger compiled from a natural-language ``proactive_trigger``.

    The orchestrator binds these to Home Assistant State-Changed events.
    """

    id: str
    agent_id: str
    source_text: str = ""
    entity_id: str
    attribute: str = "state"
    operator: str = ">"  # >, <, >=, <=, ==, !=, changed, on, off
    threshold: float | str | None = None
    reaction: str = ""
    cooldown: float = 0.0
